packages:
  - packages/*
allowBuilds:
  '@swc/core': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@begit/core@0.3.5 || 0.4.0'
  - '@turbo/darwin-64@2.10.6'
  - '@turbo/darwin-arm64@2.10.6'
  - '@turbo/linux-64@2.10.6'
  - '@turbo/linux-arm64@2.10.6'
  - '@turbo/windows-64@2.10.6'
  - '@turbo/windows-arm64@2.10.6'
  - turbo@2.10.6
