declare const S_STEP_ACTIVE = "\u25C6";
declare const S_STEP_CANCEL = "\u25A0";
declare const S_STEP_ERROR = "\u25B2";
declare const S_STEP_SUBMIT = "\u25C7";
declare const S_BAR_START = "\u250C";
declare const S_BAR = "\u2502";
declare const S_BAR_END = "\u2514";
declare const S_RADIO_ACTIVE = "\u25CF";
declare const S_RADIO_INACTIVE = "\u25CB";
declare const S_CHECKBOX_ACTIVE = "\u25FB";
declare const S_CHECKBOX_SELECTED = "\u25FC";
declare const S_CHECKBOX_INACTIVE = "\u25FB";
declare const S_PASSWORD_MASK = "\u25AA";
declare const S_BAR_H = "\u2500";
declare const S_CORNER_TOP_RIGHT = "\u256E";
declare const S_CONNECT_LEFT = "\u251C";
declare const S_CORNER_BOTTOM_RIGHT = "\u256F";
declare const S_INFO = "\u25CF";
declare const S_SUCCESS = "\u25C6";
declare const S_WARN = "\u25B2";
declare const S_ERROR = "\u25A0";
declare const strip: (str: string) => string;
declare const box: (message?: string, title?: string) => string;
export { S_CONNECT_LEFT, S_CORNER_BOTTOM_RIGHT, S_CORNER_TOP_RIGHT, S_BAR, S_BAR_START, S_BAR_END, S_BAR_H, S_INFO, S_ERROR, S_WARN, S_SUCCESS, S_RADIO_ACTIVE, S_RADIO_INACTIVE, S_PASSWORD_MASK, S_CHECKBOX_ACTIVE, S_CHECKBOX_INACTIVE, S_CHECKBOX_SELECTED, S_STEP_ACTIVE, S_STEP_ERROR, S_STEP_CANCEL, S_STEP_SUBMIT, };
declare const cancelable: <T = unknown>(prompt: Promise<symbol | T>, cancelMessage?: string) => Promise<T>;
export { strip, box, cancelable };
